In [11]:
n=[[0.4500530350481553, 0.4758324649550451, 0.59822310030917, 0.6944954799687826, 0.5098771808999082], [0.5765975732327278, 0.7124696940341102, 0.794075120583658, 0.8533377910379814, 0.690770202020202], [0.594065371490318, 0.6893952683419822, 0.8175332869762291, 0.8327446182362123, 0.6595259412304867], [0.4731083835102713, 0.5246460158455037, 0.6960972959582247, 0.7244610106659729, 0.5241483011937558], [0.518586102831052, 0.6911259157245417, 0.7722376132713767, 0.8208759796110822, 0.6232610192837467], [0.6024344477535254, 0.7564833821196111, 0.8492118679092333, 0.8749832327978667, 0.6892688246097337], [0.5110459888685989, 0.38691096460682106, 0.6288660046675962, 0.5490095156412591, 0.3940036730945822], [0.44182896097653346, 0.4500651938272704, 0.5853767863734641, 0.5828330271201874, 0.4203799357208448], [0.5316826478062294, 0.5947823992375725, 0.7871197153820966, 0.7560275551183663, 0.6407954545454546], [0.5128072027024702, 0.6923191722216695, 0.7857136725250764, 0.832960051378772, 0.6643698347107438], [0.5356698770196024, 0.6426173881624767, 0.800647282529381, 0.7931120333636836, 0.6513475665748393]]
print(n)

[[0.4500530350481553, 0.4758324649550451, 0.59822310030917, 0.6944954799687826, 0.5098771808999082], [0.5765975732327278, 0.7124696940341102, 0.794075120583658, 0.8533377910379814, 0.690770202020202], [0.594065371490318, 0.6893952683419822, 0.8175332869762291, 0.8327446182362123, 0.6595259412304867], [0.4731083835102713, 0.5246460158455037, 0.6960972959582247, 0.7244610106659729, 0.5241483011937558], [0.518586102831052, 0.6911259157245417, 0.7722376132713767, 0.8208759796110822, 0.6232610192837467], [0.6024344477535254, 0.7564833821196111, 0.8492118679092333, 0.8749832327978667, 0.6892688246097337], [0.5110459888685989, 0.38691096460682106, 0.6288660046675962, 0.5490095156412591, 0.3940036730945822], [0.44182896097653346, 0.4500651938272704, 0.5853767863734641, 0.5828330271201874, 0.4203799357208448], [0.5316826478062294, 0.5947823992375725, 0.7871197153820966, 0.7560275551183663, 0.6407954545454546], [0.5128072027024702, 0.6923191722216695, 0.7857136725250764, 0.832960051378772, 0.664

Two attributes of equal importance:   1
One attribute is slightly important over the other:   2
One attribute is very important over the other:   3
One attribute is most important over the other:   4
One attribute is extremely important over the other:   5
One attribute is exceptionally important over the other:   6
How is space attribute related to Price: 1
How is space attribute related to Power: 1
How is space attribute related to Performance: 1
How is space attribute related to Oil-Consumption: 1
How is Price attribute related to Power: 1
How is Price attribute related to Performance: 1
How is Price attribute related to Oil-consumption: 1
How is Power attribute related to Performance: 1
How is Power attribute related to Oil-consumption: 1
How is performance attribute related to Oil-Consumption: 1
[[0.  0.5 0.5 0.5 0.5]
 [0.5 0.  0.5 0.5 0.5]
 [0.5 0.5 0.  0.5 0.5]
 [0.5 0.5 0.5 0.  0.5]
 [0.5 0.5 0.5 0.5 0. ]]


In [7]:
  #-------------------USER INPUT----------------
import numpy as np

# Function to map user input to corresponding float values
def map_input_to_value(input_value):
    if input_value == 1:
        return [0.5,0.5,0.55]
    elif input_value == 2:
        return [0.55,0.6,0.7]
    elif input_value == 3:
        return [0.65,0.75,0.85]
    elif input_value == 4:
        return [0.8,0.9,1]
    elif input_value == 5:
        return [0.95,1,1]
    else:
        return None  # Invalid input

# Function to get user input
def get_input(prompt):
    while True:
        try:
            value = int(input(prompt))
            if value < 1 or value > 6:
                raise ValueError
            return value
        except ValueError:
            print("Invalid input. Please enter a number between 1 and 6.")

# Prompt user for input
print("Two attributes of equal importance:   1")
print("One attribute is very important over the other:   2")
print("One attribute is most important over the other:   3")
print("One attribute is extremely important over the other:   4")
print("One attribute is exceptionally important over the other:   5")

# Get user inputs for pairwise comparisons
n1 = map_input_to_value(get_input("How is space attribute related to Price: "))
n2 = map_input_to_value(get_input("How is space attribute related to Power: "))
n3 = map_input_to_value(get_input("How is space attribute related to Performance: "))
n4 = map_input_to_value(get_input("How is space attribute related to Oil-Consumption: "))
n6 = map_input_to_value(get_input("How is Price attribute related to Power: "))
n7 = map_input_to_value(get_input("How is Price attribute related to Performance: "))
n8 = map_input_to_value(get_input("How is Price attribute related to Oil-consumption: "))
n11 = map_input_to_value(get_input("How is Power attribute related to Performance: "))
n12 = map_input_to_value(get_input("How is Power attribute related to Oil-consumption: "))
n16 = map_input_to_value(get_input("How is performance attribute related to Oil-Consumption: "))

n1=(n1[0]+n1[1]+n1[2])/3
n2=(n2[0]+n2[1]+n3[2])/3
n3=(n3[0]+n3[1]+n3[2])/3
n4=(n4[0]+n4[1]+n4[2])/3
n6=(n6[0]+n6[1]+n6[2])/3
n7=(n7[0]+n7[1]+n7[2])/3
n8=(n8[0]+n8[1]+n8[2])/3
n11=(n11[0]+n11[1]+n11[2])/3
n12=(n12[0]+n12[1]+n12[2])/3
n16=(n16[0]+n16[1]+n16[2])/3
# Calculate the complement values
n5 = 1 - n1
n9 = 1 - n2
n10 = 1 - n6
n13 = 1 - n3
n14 = 1 - n7
n15 = 1 - n11
n17 = 1 - n4
n18 = 1 - n8
n19 = 1 - n12
n20 = 1 - n16

Two attributes of equal importance:   1
One attribute is very important over the other:   2
One attribute is most important over the other:   3
One attribute is extremely important over the other:   4
One attribute is exceptionally important over the other:   5
How is space attribute related to Price: 1
How is space attribute related to Power: 1
How is space attribute related to Performance: 1
How is space attribute related to Oil-Consumption: 1
How is Price attribute related to Power: 1
How is Price attribute related to Performance: 1
How is Price attribute related to Oil-consumption: 1
How is Power attribute related to Performance: 1
How is Power attribute related to Oil-consumption: 1
How is performance attribute related to Oil-Consumption: 1


In [6]:

print(n1)

0.5166666666666667


In [9]:
# Create an array of all the values
n_arr = [n1, n2, n3, n4, n5, n6, n7, n8, n9, n10, n11, n12, n13, n14, n15, n16, n17, n18, n19, n20]
print(n_arr)
# Construct the upper triangular matrix
matrix_size = 5
matrix = np.empty((matrix_size, matrix_size), dtype=float)

# Fill the non-diagonal elements into the matrix
count = 0
# Fill the diagonal elements with 0
np.fill_diagonal(matrix, 0)
for i in range(matrix_size):
    for j in range(matrix_size):
        if i != j:
            matrix[i, j] = n_arr[count]
            count += 1
print(matrix)

[0.5166666666666667, 0.5166666666666667, 0.5166666666666667, 0.5166666666666667, 0.4833333333333333, 0.5166666666666667, 0.5166666666666667, 0.5166666666666667, 0.4833333333333333, 0.4833333333333333, 0.5166666666666667, 0.5166666666666667, 0.4833333333333333, 0.4833333333333333, 0.4833333333333333, 0.5166666666666667, 0.4833333333333333, 0.4833333333333333, 0.4833333333333333, 0.4833333333333333]
[[0.         0.51666667 0.51666667 0.51666667 0.51666667]
 [0.48333333 0.         0.51666667 0.51666667 0.51666667]
 [0.48333333 0.48333333 0.         0.51666667 0.51666667]
 [0.48333333 0.48333333 0.48333333 0.         0.51666667]
 [0.48333333 0.48333333 0.48333333 0.48333333 0.        ]]


In [12]:
#---------------------------------PERMANENT FUNCTION CALCULATION----------------------------------
import itertools
import numpy as np
def mat_in(n_arr,p,x):
    c=0
    for i in range(matrix_size):
        for j in range(matrix_size):
            if i==j:
                matrix[i, j] = p[x][c]
                c += 1
    return matrix
def permanent_function(mat):
    A = mat
# Generate all permutations of the indices (1, 2, 3, 4, 5)
    permutations = itertools.permutations(range(5))
# Calculate the permanent
    permanent_value = 0
    for perm in permutations:
        product = 1
        for i in range(5):
            product *= A[i, perm[i]]
        permanent_value += product
    return permanent_value
r=[]

for i in range(0,11):
    mat=mat_in(n_arr,n,i)
    per1=permanent_function(mat)
    r.append(per1)
print(mat)
print(r)

[[0.53566988 0.51666667 0.51666667 0.51666667 0.51666667]
 [0.48333333 0.64261739 0.51666667 0.51666667 0.51666667]
 [0.48333333 0.48333333 0.80064728 0.51666667 0.51666667]
 [0.48333333 0.48333333 0.48333333 0.79311203 0.51666667]
 [0.48333333 0.48333333 0.48333333 0.48333333 0.65134757]]
[4.086079890188474, 5.851196244149341, 5.773621826525702, 4.446233384489972, 5.391469674923643, 6.1970990529600725, 3.6830408481307573, 3.7049886010396467, 5.153820734864167, 5.5246056375200805, 5.389893468705059]


In [13]:
#----------------RANKING THE CARS BASED ON THE PERMANENT FUNCTION CALCULATED-----------------
res={}
my_dict={}
keys=['Honda','Hyundai','Isuzu','Kia','Land-rover','Nexon','Porsche','Swift','Tata','Thar','Volvo']
i=0
for k in keys:
    my_dict[k]=r[i]
    i=i+1
i=0
print("CARS AFTER CALCULATING THE PERMANENT FUNCTION ")
for key, value in my_dict.items():
    print(f"{i} {key}: {value}")
#     print(value[0],' ',value[1],' ',value[2])
    i=i+1

print('-------CARS RANKED USING GTMA------')
i=1
sorted_dict = dict(sorted(my_dict.items(), key=lambda item: item[1], reverse=True))
for key, value in sorted_dict.items():
    print(f"{i} {key}: {value}")
    i=i+1


CARS AFTER CALCULATING THE PERMANENT FUNCTION 
0 Honda: 4.086079890188474
1 Hyundai: 5.851196244149341
2 Isuzu: 5.773621826525702
3 Kia: 4.446233384489972
4 Land-rover: 5.391469674923643
5 Nexon: 6.1970990529600725
6 Porsche: 3.6830408481307573
7 Swift: 3.7049886010396467
8 Tata: 5.153820734864167
9 Thar: 5.5246056375200805
10 Volvo: 5.389893468705059
-------CARS RANKED USING GTMA------
1 Nexon: 6.1970990529600725
2 Hyundai: 5.851196244149341
3 Isuzu: 5.773621826525702
4 Thar: 5.5246056375200805
5 Land-rover: 5.391469674923643
6 Volvo: 5.389893468705059
7 Tata: 5.153820734864167
8 Kia: 4.446233384489972
9 Honda: 4.086079890188474
10 Swift: 3.7049886010396467
11 Porsche: 3.6830408481307573
