In [1]:
#space
q_1_pos=[[138, 126, 136, 154, 140, 134, 151, 166, 140, 123], [202, 180, 191, 212, 195, 214, 222, 211, 244, 190], [204, 195, 212, 238, 194, 213, 236, 203, 231, 191], [149, 134, 143, 154, 138, 130, 157, 173, 152, 127], [184, 162, 163, 203, 161, 193, 196, 182, 195, 181], [223, 188, 216, 239, 219, 235, 227, 211, 244, 201], [156, 136, 161, 143, 145, 136, 156, 151, 144, 119], [115, 115, 122, 123, 110, 120, 142, 116, 141, 102], [156, 115, 153, 170, 148, 162, 177, 149, 193, 143], [207, 136, 151, 205, 164, 203, 231, 161, 197, 163], [154, 140, 144, 150, 145, 153, 170, 159, 157, 141]]
q_1_neu=[[147, 165, 143, 118, 118, 147, 137, 115, 150, 128], [104, 110, 118, 99, 96, 99, 75, 61, 80, 80], [84, 100, 101, 80, 94, 97, 76, 65, 103, 90], [153, 168, 146, 128, 133, 168, 141, 110, 148, 143], [87, 104, 106, 85, 91, 95, 66, 57, 103, 68], [77, 94, 110, 68, 86, 92, 71, 59, 89, 71], [129, 153, 126, 111, 106, 141, 129, 117, 125, 130], [95, 115, 102, 82, 85, 105, 59, 66, 75, 80], [115, 131, 110, 91, 97, 121, 90, 65, 95, 115], [103, 155, 153, 92, 119, 125, 82, 78, 119, 107], [90, 88, 103, 89, 86, 94, 70, 52, 86, 79]]
q_1_neg=[[150, 144, 156, 163, 177, 154, 147, 154, 145, 184], [140, 156, 137, 135, 155, 133, 149, 174, 122, 176], [154, 147, 129, 124, 154, 132, 130, 174, 108, 161], [133, 133, 146, 153, 164, 137, 137, 152, 135, 165], [163, 168, 165, 146, 182, 146, 172, 195, 136, 185], [145, 163, 119, 138, 140, 118, 147, 175, 112, 173], [111, 107, 109, 142, 145, 119, 111, 128, 127, 147], [144, 124, 130, 149, 159, 129, 153, 172, 138, 172], [118, 143, 126, 128, 144, 106, 122, 175, 101, 131], [149, 168, 155, 162, 176, 131, 146, 220, 143, 189], [118, 134, 115, 123, 131, 115, 122, 151, 119, 142]]
#price
q_2_pos=[[139, 161, 135, 141, 172, 140, 172, 142, 146, 148], [243, 257, 255, 239, 245, 239, 296, 251, 260, 262], [251, 245, 254, 245, 215, 225, 260, 201, 252, 241], [160, 179, 139, 150, 185, 137, 165, 164, 154, 148], [226, 237, 240, 243, 236, 237, 271, 219, 243, 234], [293, 280, 281, 302, 275, 271, 297, 268, 290, 282], [94, 89, 102, 118, 115, 79, 128, 84, 104, 97], [103, 112, 111, 120, 131, 83, 118, 99, 110, 103], [173, 187, 175, 168, 180, 168, 192, 160, 180, 190], [248, 263, 236, 225, 237, 226, 278, 218, 243, 251], [197, 194, 176, 174, 186, 169, 202, 171, 173, 179]]
q_2_neu=[[131, 166, 153, 139, 114, 157, 121, 137, 127, 113], [101, 79, 116, 107, 95, 104, 59, 90, 80, 88], [85, 103, 121, 94, 111, 117, 88, 116, 84, 90], [155, 159, 191, 154, 127, 192, 144, 146, 135, 150], [96, 98, 114, 91, 88, 107, 73, 88, 83, 90], [74, 76, 87, 62, 60, 94, 63, 64, 60, 66], [160, 192, 173, 140, 149, 178, 153, 182, 153, 160], [127, 133, 139, 137, 101, 164, 130, 138, 115, 130], [91, 93, 112, 98, 93, 122, 89, 96, 90, 88], [123, 106, 152, 122, 118, 126, 89, 130, 111, 92], [68, 80, 95, 84, 80, 93, 72, 88, 87, 81]]
q_2_neg=[[165, 108, 147, 155, 149, 138, 142, 156, 162, 174], [102, 110, 75, 100, 106, 103, 91, 105, 106, 96], [106, 94, 67, 103, 116, 100, 94, 125, 106, 111], [120, 97, 105, 131, 123, 106, 126, 125, 146, 137], [112, 99, 80, 100, 110, 90, 90, 127, 108, 110], [78, 89, 77, 81, 110, 80, 85, 113, 95, 97], [142, 115, 121, 138, 132, 139, 115, 130, 139, 139], [124, 109, 104, 97, 122, 107, 106, 117, 129, 121], [125, 109, 102, 123, 116, 99, 108, 133, 119, 111], [88, 90, 71, 112, 104, 107, 92, 111, 105, 116], [97, 88, 91, 104, 96, 100, 88, 103, 102, 102]]
#power
q_3_pos=[[195, 200, 206, 227, 221, 204, 200, 189, 206, 181], [315, 313, 292, 323, 316, 313, 297, 290, 313, 296], [306, 303, 303, 332, 314, 309, 304, 285, 305, 296], [240, 239, 260, 256, 238, 231, 237, 220, 266, 224], [281, 292, 297, 318, 308, 292, 288, 276, 293, 292], [339, 341, 325, 336, 348, 314, 308, 324, 332, 317], [171, 163, 196, 196, 192, 170, 194, 184, 195, 172], [167, 166, 169, 164, 167, 172, 160, 157, 188, 159], [259, 261, 254, 258, 271, 265, 264, 243, 273, 258], [313, 311, 307, 314, 320, 302, 297, 277, 319, 298], [246, 238, 251, 248, 242, 243, 242, 235, 242, 247]]
q_3_neu=[[119, 123, 99, 85, 89, 108, 110, 109, 106, 100], [67, 53, 69, 60, 61, 54, 76, 66, 50, 51], [76, 69, 67, 46, 71, 67, 78, 72, 84, 69], [97, 103, 85, 80, 87, 121, 102, 118, 78, 84], [71, 59, 50, 39, 51, 52, 67, 52, 53, 50], [65, 54, 74, 53, 47, 62, 76, 55, 52, 55], [141, 143, 125, 104, 99, 127, 123, 117, 108, 113], [81, 88, 75, 63, 51, 79, 90, 68, 67, 72], [64, 54, 52, 53, 59, 63, 67, 69, 61, 51], [72, 80, 59, 61, 66, 74, 92, 82, 59, 71], [67, 71, 59, 44, 55, 62, 67, 66, 60, 47]]
q_3_neg=[[121, 112, 130, 123, 125, 123, 125, 137, 123, 154], [64, 80, 85, 63, 69, 79, 73, 90, 83, 99], [60, 70, 72, 64, 57, 66, 60, 85, 53, 77], [98, 93, 90, 99, 110, 83, 96, 97, 91, 127], [82, 83, 87, 77, 75, 90, 79, 106, 88, 92], [41, 50, 46, 56, 50, 69, 61, 66, 61, 73], [84, 90, 75, 96, 105, 99, 79, 95, 93, 111], [106, 100, 110, 127, 136, 103, 104, 129, 99, 123], [66, 74, 83, 78, 59, 61, 58, 77, 55, 80], [74, 68, 93, 84, 73, 83, 70, 100, 81, 90], [49, 53, 52, 70, 65, 57, 53, 61, 60, 68]]
#performance
q_4_pos=[[261, 225, 246, 261, 252, 223, 241, 244, 251, 223], [380, 352, 360, 378, 357, 339, 355, 354, 353, 344], [359, 334, 347, 354, 339, 337, 339, 323, 350, 329], [274, 251, 256, 279, 245, 245, 259, 265, 271, 238], [338, 320, 317, 341, 337, 314, 326, 329, 329, 322], [384, 354, 371, 387, 370, 363, 362, 360, 362, 359], [182, 151, 190, 187, 152, 151, 170, 182, 188, 136], [166, 139, 163, 165, 161, 156, 178, 174, 168, 143], [273, 255, 255, 264, 275, 254, 242, 266, 265, 252], [385, 362, 379, 387, 350, 346, 377, 344, 367, 346], [270, 247, 259, 265, 259, 235, 263, 261, 262, 248]]
q_4_neu=[[100, 128, 92, 100, 84, 113, 106, 114, 87, 128], [24, 32, 29, 24, 26, 35, 32, 28, 23, 36], [37, 38, 32, 24, 33, 32, 34, 49, 27, 40], [96, 107, 97, 83, 67, 98, 105, 104, 82, 111], [39, 44, 44, 33, 29, 38, 40, 38, 34, 40], [24, 30, 26, 21, 19, 24, 30, 32, 27, 34], [117, 131, 108, 99, 95, 134, 120, 108, 99, 123], [98, 132, 96, 104, 73, 104, 88, 97, 75, 113], [51, 56, 49, 52, 42, 48, 64, 45, 41, 55], [22, 30, 23, 18, 21, 24, 21, 29, 18, 23], [38, 42, 45, 37, 38, 52, 38, 53, 35, 43]]
q_4_neg=[[74, 82, 97, 74, 99, 99, 88, 77, 97, 84], [42, 62, 57, 44, 63, 72, 59, 64, 70, 66], [46, 70, 63, 64, 70, 73, 69, 70, 65, 73], [65, 77, 82, 73, 123, 92, 71, 66, 82, 86], [57, 70, 73, 60, 68, 82, 68, 67, 71, 72], [37, 61, 48, 37, 56, 58, 53, 53, 56, 52], [97, 114, 98, 110, 149, 111, 106, 106, 109, 137], [90, 83, 95, 85, 120, 94, 88, 83, 111, 98], [65, 78, 85, 73, 72, 87, 83, 78, 83, 82], [52, 67, 57, 54, 88, 89, 61, 86, 74, 90], [54, 73, 58, 60, 65, 75, 61, 48, 65, 71]]
#oil
q_5_pos=[[129, 123, 117, 118, 138, 106, 127, 84, 127, 116], [161, 186, 170, 181, 183, 156, 182, 145, 180, 192], [165, 166, 156, 166, 148, 144, 192, 137, 181, 173], [130, 114, 113, 134, 124, 107, 154, 92, 140, 141], [154, 149, 136, 141, 136, 145, 177, 119, 149, 159], [184, 203, 187, 195, 195, 156, 197, 158, 206, 189], [87, 82, 81, 110, 95, 62, 109, 68, 86, 81], [104, 97, 84, 108, 102, 75, 109, 61, 93, 92], [127, 131, 131, 140, 149, 131, 136, 113, 143, 147], [187, 211, 167, 194, 168, 170, 216, 158, 203, 215], [139, 148, 132, 128, 139, 113, 149, 112, 147, 134]]
q_5_neu=[[195, 208, 223, 220, 189, 224, 225, 260, 199, 220], [207, 185, 223, 201, 188, 200, 211, 245, 177, 195], [184, 197, 209, 219, 211, 206, 188, 239, 186, 205], [202, 218, 217, 221, 188, 208, 205, 242, 186, 199], [188, 205, 225, 232, 213, 203, 192, 251, 197, 203], [167, 164, 186, 179, 158, 190, 172, 213, 150, 185], [181, 188, 202, 198, 184, 192, 166, 209, 161, 203], [127, 134, 140, 141, 120, 137, 135, 161, 134, 133], [192, 186, 189, 197, 166, 185, 200, 222, 178, 179], [176, 152, 210, 186, 177, 182, 171, 204, 151, 166], [154, 158, 162, 167, 142, 167, 164, 188, 152, 167]]
q_5_neg=[[111, 104, 95, 97, 108, 105, 83, 91, 109, 99], [78, 75, 53, 64, 75, 90, 53, 56, 89, 59], [93, 79, 77, 57, 83, 92, 62, 66, 75, 64], [103, 103, 105, 80, 123, 120, 76, 101, 109, 95], [92, 80, 73, 61, 85, 86, 65, 64, 88, 72], [94, 78, 72, 71, 92, 99, 76, 74, 89, 71], [128, 126, 113, 88, 117, 142, 121, 119, 149, 112], [123, 123, 130, 105, 132, 142, 110, 132, 127, 129], [70, 72, 69, 52, 74, 73, 53, 54, 68, 63], [96, 96, 82, 79, 114, 107, 72, 97, 105, 78], [69, 56, 68, 67, 81, 82, 49, 62, 63, 61]]

In [2]:
#-------------CALCULATION OF SENTIMENT ORIENTATION------------------
#space
p1 = []
n1 = []
num_elements = len(q_1_pos)
num_values_per_sublist = min(10, len(q_1_pos[0]))  

for j in range(num_elements):
    sub_p1 = []  
    sub_n1 = []
    for i in range(num_values_per_sublist):
        t = q_1_pos[j][i] + q_1_neu[j][i] + q_1_neg[j][i]
        a = q_1_pos[j][i] / t if t != 0 else 0
        b = q_1_neg[j][i] / t if t != 0 else 0
        sub_p1.append(a)
        sub_n1.append(b)
    p1.append(sub_p1)  
    n1.append(sub_n1)

#price
p2 = []
n2 = []
num_elements = len(q_2_pos)
num_values_per_sublist = min(10, len(q_2_pos[0]))  

for j in range(num_elements):
    sub_p1 = []  
    sub_n1 = []# Create an empty sublist for p1
    for i in range(num_values_per_sublist):
        t = q_2_pos[j][i] + q_2_neu[j][i] + q_2_neg[j][i]
        a = q_2_pos[j][i] / t if t != 0 else 0
        b = q_2_neg[j][i] / t if t != 0 else 0
        sub_p1.append(a)
        sub_n1.append(b)
    p2.append(sub_p1)  
    n2.append(sub_n1)

#power
p3 = []
n3 = []
num_elements = len(q_3_pos)
num_values_per_sublist = min(10, len(q_3_pos[0]))  

for j in range(num_elements):
    sub_p1 = []  
    sub_n1 = []
    for i in range(num_values_per_sublist):
        t = q_3_pos[j][i] + q_3_neu[j][i] + q_3_neg[j][i]
        a = q_3_pos[j][i] / t if t != 0 else 0
        b = q_3_neg[j][i] / t if t != 0 else 0
        sub_p1.append(a)
        sub_n1.append(b)
    p3.append(sub_p1)  
    n3.append(sub_n1)

#performance
p4 = []
n4 = []
num_elements = len(q_4_pos)
num_values_per_sublist = min(10, len(q_4_pos[0]))  

for j in range(num_elements):
    sub_p1 = []  
    sub_n1 = []
    for i in range(num_values_per_sublist):
        t = q_4_pos[j][i] + q_4_neu[j][i] + q_4_neg[j][i]
        a = q_4_pos[j][i] / t if t != 0 else 0
        b = q_4_neg[j][i] / t if t != 0 else 0# Handle division by zero
        sub_p1.append(a)
        sub_n1.append(b)
    p4.append(sub_p1)  
    n4.append(sub_n1)

#oil
p5 = []
n5 = []
num_elements = len(q_5_pos)
num_values_per_sublist = min(10, len(q_5_pos[0]))  # sublist size

for j in range(num_elements):
    sub_p1 = []  
    sub_n1 = []
    for i in range(num_values_per_sublist):
        t = q_5_pos[j][i] + q_5_neu[j][i] + q_5_neg[j][i]
        a = q_5_pos[j][i] / t if t != 0 else 0
        b = q_5_neg[j][i] / t if t != 0 else 0# Handle division by zero
        sub_p1.append(a)
        sub_n1.append(b)
    p5.append(sub_p1)  
    n5.append(sub_n1)
print(n1)

[[0.3448275862068966, 0.3310344827586207, 0.3586206896551724, 0.37471264367816093, 0.4068965517241379, 0.35402298850574715, 0.33793103448275863, 0.35402298850574715, 0.3333333333333333, 0.42298850574712643], [0.31390134529147984, 0.34977578475336324, 0.3071748878923767, 0.30269058295964124, 0.3475336322869955, 0.2982062780269058, 0.33408071748878926, 0.3901345291479821, 0.273542600896861, 0.39461883408071746], [0.34841628959276016, 0.332579185520362, 0.2918552036199095, 0.28054298642533937, 0.34841628959276016, 0.2986425339366516, 0.29411764705882354, 0.3936651583710407, 0.24434389140271492, 0.36425339366515835], [0.3057471264367816, 0.3057471264367816, 0.335632183908046, 0.35172413793103446, 0.37701149425287356, 0.31494252873563217, 0.31494252873563217, 0.34942528735632183, 0.3103448275862069, 0.3793103448275862], [0.37557603686635943, 0.3870967741935484, 0.38018433179723504, 0.33640552995391704, 0.41935483870967744, 0.33640552995391704, 0.39631336405529954, 0.44930875576036866, 0.313

In [3]:
#---------------CONFIDENCE INTERVAL CALCULATION---------------
import math
import numpy as np
def formula(pos,neg):
    a=[]
    mp=np.mean(pos)
    mn=np.mean(neg)
    sp=np.std(pos)
    sn=np.std(neg)
    up=mp+(1.96*(sp/math.sqrt(10)))
    un=mp-(1.96*(sp/math.sqrt(10)))
    vp=mn+(1.96*(sn/math.sqrt(10)))
    vn=mn-(1.96*(sn/math.sqrt(10)))
    a=[[un,up],[vn,vp]]
    return a
#space
in1=[]
for i in range(len(q_1_pos)):
        in1.append(formula(p1[i],n1[i]))
print('in1:')
print(in1)
#price
in2=[]
for i in range(len(q_2_pos)):
        in2.append(formula(p2[i],n2[i]))
print('in2')
print(in2)
#power
in3=[]
for i in range(len(q_3_pos)):
        in3.append(formula(p3[i],n3[i]))
print('in3')
print(in3)
#performance
in4=[]
for i in range(len(q_4_pos)):
        in4.append(formula(p4[i],n4[i]))
print('in4')
print(in4)
#oil
in5=[]
for i in range(len(q_5_pos)):
        in5.append(formula(p5[i],n5[i]))
print('in5')
print(in5)

in1:
[[[0.3060676628434182, 0.34128865899566235], [0.34356773418040104, 0.38011042673913925]], [[0.4375649459762481, 0.4866503006605232], [0.30779538755766994, 0.3545364510073525]], [[0.45544404865413923, 0.5024745033820598], [0.2931283377619163, 0.3462381780751877]], [[0.31586825836434784, 0.3540167991069165], [0.3176931815483136, 0.3512723356930657]], [[0.39849247322912057, 0.4402172041902342], [0.3564502468916293, 0.4076050526475412]], [[0.4721608570752138, 0.517951502475348], [0.291671041946311, 0.35102558726717226]], [[0.3470434821061536, 0.3837645987019273], [0.29147140918607173, 0.3378215201068575]], [[0.3197816951058878, 0.3615742370975021], [0.38666629597614216, 0.4438421786001289]], [[0.370662640273309, 0.4344787479014982], [0.30065236119817446, 0.36464326862187685]], [[0.3568868981666139, 0.4352699645784842], [0.3237709570208813, 0.39039026302269164]], [[0.40283333430331564, 0.4330782679066291], [0.3310089004272169, 0.370648558136319]]]
in2
[[[0.32533911914396574, 0.36247697

In [4]:
#-----------------to print the round off list of ivifs of 11 cars attribute wise--------------
def round_nested_lists(nested_list):
    for i in range(len(nested_list)):
        for j in range(len(nested_list[i])):
            for k in range(len(nested_list[i][j])):
                nested_list[i][j][k] = round(nested_list[i][j][k], 3)
    return nested_list

# Round off each list to 3 decimal places
in1_rounded = round_nested_lists(in1)
in2_rounded = round_nested_lists(in2)
in3_rounded = round_nested_lists(in3)
in4_rounded = round_nested_lists(in4)
in5_rounded = round_nested_lists(in5)

# Print rounded lists
print("in1_rounded:", in1_rounded)
print("in2_rounded:", in2_rounded)
print("in3_rounded:", in3_rounded)
print("in4_rounded:", in4_rounded)
print("in5_rounded:", in5_rounded)


in1_rounded: [[[0.306, 0.341], [0.344, 0.38]], [[0.438, 0.487], [0.308, 0.355]], [[0.455, 0.502], [0.293, 0.346]], [[0.316, 0.354], [0.318, 0.351]], [[0.398, 0.44], [0.356, 0.408]], [[0.472, 0.518], [0.292, 0.351]], [[0.347, 0.384], [0.291, 0.338]], [[0.32, 0.362], [0.387, 0.444]], [[0.371, 0.434], [0.301, 0.365]], [[0.357, 0.435], [0.324, 0.39]], [[0.403, 0.433], [0.331, 0.371]]]
in2_rounded: [[[0.325, 0.362], [0.319, 0.369]], [[0.549, 0.593], [0.209, 0.236]], [[0.515, 0.566], [0.21, 0.252]], [[0.342, 0.385], [0.259, 0.3]], [[0.531, 0.568], [0.218, 0.255]], [[0.623, 0.653], [0.186, 0.221]], [[0.232, 0.278], [0.315, 0.346]], [[0.286, 0.33], [0.304, 0.338]], [[0.44, 0.472], [0.278, 0.311]], [[0.505, 0.552], [0.199, 0.235]], [[0.484, 0.522], [0.258, 0.278]]]
in3_rounded: [[[0.448, 0.485], [0.277, 0.308]], [[0.672, 0.703], [0.161, 0.191]], [[0.676, 0.708], [0.137, 0.163]], [[0.534, 0.575], [0.21, 0.243]], [[0.66, 0.693], [0.186, 0.21]], [[0.721, 0.755], [0.115, 0.143]], [[0.444, 0.482], [

In [5]:
#------------------CALCULATING MAXIMUM FOR NORMALIZATION-------------
b=[]
norm=[]
list=[in1,in2,in3,in4,in5]
for sub in list:
    for l in sub:
        a=l[0][1]+l[1][1]
        b.append(a)
sublist_length = 11
norm = [b[i:i+sublist_length] for i in range(0, len(b), sublist_length)]
# print(norm)
max_values = [max(sublist) for sublist in norm]
print(max_values)

[0.869, 0.874, 0.9029999999999999, 0.992, 0.66]


In [6]:
#----------------NORMALIZATION------------------
def normalize(arr, x):
    for sublist in arr:
        for i in range(len(sublist)):
            sublist[i][0] = sublist[i][0] / x
            sublist[i][1] = sublist[i][1] / x
    return arr
z=[]
i=0
for l in list:
    a=normalize(l,max_values[i])
    i=i+1
    print(a)

[[[0.3521288837744534, 0.3924050632911393], [0.3958573072497123, 0.4372842347525892]], [[0.5040276179516686, 0.5604142692750288], [0.35443037974683544, 0.4085155350978136]], [[0.523590333716916, 0.5776754890678941], [0.33716915995397007, 0.39815880322209435]], [[0.36363636363636365, 0.40736478711162255], [0.3659378596087457, 0.4039125431530495]], [[0.45799769850402766, 0.5063291139240507], [0.4096662830840046, 0.46950517836593786]], [[0.5431530494821634, 0.5960874568469505], [0.33601841196777904, 0.4039125431530495]], [[0.3993095512082854, 0.4418872266973533], [0.334867663981588, 0.3889528193325662]], [[0.36823935558112775, 0.41657077100115075], [0.4453394706559264, 0.5109321058688148]], [[0.42692750287687, 0.4994246260069045], [0.34637514384349827, 0.42002301495972383]], [[0.4108170310701956, 0.5005753739930955], [0.37284234752589185, 0.44879171461449946]], [[0.4637514384349828, 0.4982738780207135], [0.380897583429229, 0.42692750287687]]]
[[[0.3718535469107552, 0.41418764302059496], [

In [7]:
#--------------IVIFS FOR 11 CARS REGARDING 5 ATTRIBUTES-----------------
import numpy as np
cars=['honda','hyundai','isuzu','kia','land-rover','nexon','porsche','swift','tata','thar','volvo']
all_data = np.concatenate((in1, in2, in3, in4, in5), axis=0)
# Create the dictionary to store the data
cars_dict = {}
# Extract and store sublists for each key
for i in range(11):
    key = cars[i]
    sublist = all_data[i::11]  # Get every 11th sublist starting from i
    cars_dict[key] = sublist.tolist()  # Convert NumPy array to list
print(cars_dict)

{'honda': [[[0.3521288837744534, 0.3924050632911393], [0.3958573072497123, 0.4372842347525892]], [[0.3718535469107552, 0.41418764302059496], [0.36498855835240274, 0.42219679633867274]], [[0.496124031007752, 0.5370985603543743], [0.30675526024363237, 0.3410852713178295]], [[0.5423387096774194, 0.5826612903225806], [0.1875, 0.2157258064516129]], [[0.3818181818181818, 0.4439393939393939], [0.33030303030303027, 0.36666666666666664]]], 'hyundai': [[[0.5040276179516686, 0.5604142692750288], [0.35443037974683544, 0.4085155350978136]], [[0.6281464530892449, 0.6784897025171625], [0.23913043478260868, 0.27002288329519447]], [[0.744186046511628, 0.7785160575858251], [0.17829457364341086, 0.21151716500553713]], [[0.7903225806451614, 0.8245967741935484], [0.1219758064516129, 0.14818548387096772]], [[0.5590909090909091, 0.6196969696969696], [0.20757575757575758, 0.2636363636363636]]], 'isuzu': [[[0.523590333716916, 0.5776754890678941], [0.33716915995397007, 0.39815880322209435]], [[0.589244851258581

In [8]:
#-----------------round off-------------------
def round_numbers_in_dict(input_dict):
    output_dict = {}
    for key, value in input_dict.items():
        output_dict[key] = []
        for inner_list in value:
            new_inner_list = []
            for inner_tuple in inner_list:
                new_inner_tuple = [round(num, 3) for num in inner_tuple]
                new_inner_list.append(new_inner_tuple)
            output_dict[key].append(new_inner_list)
    return output_dict

# Dictionary with rounded numbers to 3 decimal places
rounded_dict = round_numbers_in_dict(cars_dict)
print(rounded_dict)

{'honda': [[[0.352, 0.392], [0.396, 0.437]], [[0.372, 0.414], [0.365, 0.422]], [[0.496, 0.537], [0.307, 0.341]], [[0.542, 0.583], [0.188, 0.216]], [[0.382, 0.444], [0.33, 0.367]]], 'hyundai': [[[0.504, 0.56], [0.354, 0.409]], [[0.628, 0.678], [0.239, 0.27]], [[0.744, 0.779], [0.178, 0.212]], [[0.79, 0.825], [0.122, 0.148]], [[0.559, 0.62], [0.208, 0.264]]], 'isuzu': [[[0.524, 0.578], [0.337, 0.398]], [[0.589, 0.648], [0.24, 0.288]], [[0.749, 0.784], [0.152, 0.181]], [[0.763, 0.793], [0.14, 0.162]], [[0.524, 0.592], [0.232, 0.282]]], 'kia': [[[0.364, 0.407], [0.366, 0.404]], [[0.391, 0.441], [0.296, 0.343]], [[0.591, 0.637], [0.233, 0.269]], [[0.58, 0.617], [0.166, 0.213]], [[0.397, 0.473], [0.323, 0.385]]], 'land-rover': [[[0.458, 0.506], [0.41, 0.47]], [[0.608, 0.65], [0.249, 0.292]], [[0.731, 0.767], [0.206, 0.233]], [[0.748, 0.773], [0.15, 0.169]], [[0.48, 0.544], [0.244, 0.291]]], 'nexon': [[[0.543, 0.596], [0.336, 0.404]], [[0.713, 0.747], [0.213, 0.253]], [[0.798, 0.836], [0.127,

In [9]:
#----------------IVIFS TO SCORE CALCULATION--------------
p=[]
a=[]
ar=[]
for i in range(11):
    sublist = all_data[i::11]  # Get every 11th sublist starting from i
    p.append(sublist.tolist())  # Convert NumPy array to list
# print(p)

# Calculate the mean and overwrite the values
for sublist in p:
    for pair in sublist:
        s = (pair[0][0] + pair[0][0] * (1 - pair[0][0] - pair[1][0]) + pair[0][1] + pair[0][1] * (1 - pair[0][1] - pair[1][1]))/2
        pair[0]= s
# Display the updated list
for sub in p:
    for l in sub:
        a.append(l[0])
print(a)

# Define the length of sublists
sublist_length = 5
n = [a[i:i+sublist_length] for i in range(0, len(a), sublist_length)]
print(n)

[0.4500530350481553, 0.4758324649550451, 0.59822310030917, 0.6944954799687826, 0.5098771808999082, 0.5765975732327278, 0.7124696940341102, 0.794075120583658, 0.8533377910379814, 0.690770202020202, 0.594065371490318, 0.6893952683419822, 0.8175332869762291, 0.8327446182362123, 0.6595259412304867, 0.4731083835102713, 0.5246460158455037, 0.6960972959582247, 0.7244610106659729, 0.5241483011937558, 0.518586102831052, 0.6911259157245417, 0.7722376132713767, 0.8208759796110822, 0.6232610192837467, 0.6024344477535254, 0.7564833821196111, 0.8492118679092333, 0.8749832327978667, 0.6892688246097337, 0.5110459888685989, 0.38691096460682106, 0.6288660046675962, 0.5490095156412591, 0.3940036730945822, 0.44182896097653346, 0.4500651938272704, 0.5853767863734641, 0.5828330271201874, 0.4203799357208448, 0.5316826478062294, 0.5947823992375725, 0.7871197153820966, 0.7560275551183663, 0.6407954545454546, 0.5128072027024702, 0.6923191722216695, 0.7857136725250764, 0.832960051378772, 0.6643698347107438, 0.53

In [10]:
#-------------------USER INPUT----------------
import numpy as np

# Function to map user input to corresponding float values
def map_input_to_value(input_value):
    if input_value == 1:
        return 0.5
    elif input_value == 2:
        return 0.6
    elif input_value == 3:
        return 0.7
    elif input_value == 4:
        return 0.8
    elif input_value == 5:
        return 0.9
    elif input_value == 6:
        return 1.0
    else:
        return None  # Invalid input

# Function to get user input
def get_input(prompt):
    while True:
        try:
            value = int(input(prompt))
            if value < 1 or value > 6:
                raise ValueError
            return value
        except ValueError:
            print("Invalid input. Please enter a number between 1 and 6.")

# Prompt user for input
print("Two attributes of equal importance:   1")
print("One attribute is slightly important over the other:   2")
print("One attribute is very important over the other:   3")
print("One attribute is most important over the other:   4")
print("One attribute is extremely important over the other:   5")
print("One attribute is exceptionally important over the other:   6")

# Get user inputs for pairwise comparisons
n1 = map_input_to_value(get_input("How is space attribute related to Price: "))
n2 = map_input_to_value(get_input("How is space attribute related to Power: "))
n3 = map_input_to_value(get_input("How is space attribute related to Performance: "))
n4 = map_input_to_value(get_input("How is space attribute related to Oil-Consumption: "))
n6 = map_input_to_value(get_input("How is Price attribute related to Power: "))
n7 = map_input_to_value(get_input("How is Price attribute related to Performance: "))
n8 = map_input_to_value(get_input("How is Price attribute related to Oil-consumption: "))
n11 = map_input_to_value(get_input("How is Power attribute related to Performance: "))
n12 = map_input_to_value(get_input("How is Power attribute related to Oil-consumption: "))
n16 = map_input_to_value(get_input("How is performance attribute related to Oil-Consumption: "))

# Calculate the complement values
n5 = 1 - n1
n9 = 1 - n2
n10 = 1 - n6
n13 = 1 - n3
n14 = 1 - n7
n15 = 1 - n11
n17 = 1 - n4
n18 = 1 - n8
n19 = 1 - n12
n20 = 1 - n16

# Create an array of all the values
n_arr = [n1, n2, n3, n4, n5, n6, n7, n8, n9, n10, n11, n12, n13, n14, n15, n16, n17, n18, n19, n20]

# Construct the upper triangular matrix
matrix_size = 5
matrix = np.empty((matrix_size, matrix_size), dtype=float)

# Fill the non-diagonal elements into the matrix
count = 0
# Fill the diagonal elements with 0
np.fill_diagonal(matrix, 0)
for i in range(matrix_size):
    for j in range(matrix_size):
        if i != j:
            matrix[i, j] = n_arr[count]
            count += 1
print(matrix)

Two attributes of equal importance:   1
One attribute is slightly important over the other:   2
One attribute is very important over the other:   3
One attribute is most important over the other:   4
One attribute is extremely important over the other:   5
One attribute is exceptionally important over the other:   6
How is space attribute related to Price: 1
How is space attribute related to Power: 1
How is space attribute related to Performance: 1
How is space attribute related to Oil-Consumption: 1
How is Price attribute related to Power: 1
How is Price attribute related to Performance: 1
How is Price attribute related to Oil-consumption: 1
How is Power attribute related to Performance: 1
How is Power attribute related to Oil-consumption: 1
How is performance attribute related to Oil-Consumption: 1
[[0.  0.5 0.5 0.5 0.5]
 [0.5 0.  0.5 0.5 0.5]
 [0.5 0.5 0.  0.5 0.5]
 [0.5 0.5 0.5 0.  0.5]
 [0.5 0.5 0.5 0.5 0. ]]


In [36]:
n1=1
n2=1
n3=1
n4=1
n5=0
n6=0.5
n7=0.5
n8=0.5
n9=0
n10=0.5
n11=0.5
n12=0.5
n13=0
n14=0.5
n15=0.5
n16=0.5
n17=0
n18=0.5
n19=0.5
n20=0.5
n_arr=[n1,n2,n3,n4,n5,n6,n7,n8,n9,n10,n11,n12,n13,n14,n15,n16,n17,n18,n19,n20]
matrix_size= 5
matrix=np.empty((5,5),dtype=float)
# Fill the non-diagonal elements into the matrix
count = 0
for i in range(matrix_size):
    for j in range(matrix_size):
        if i != j:
            matrix[i, j] = n_arr[count]
            count += 1
print(matrix)

[[0.53573078 1.         1.         1.         1.        ]
 [0.         0.64255941 0.5        0.5        0.5       ]
 [0.         0.5        0.80061135 0.5        0.5       ]
 [0.         0.5        0.5        0.79298617 0.5       ]
 [0.         0.5        0.5        0.5        0.65115063]]


In [11]:
#---------------------------------PERMANENT FUNCTION CALCULATION----------------------------------
import itertools
import numpy as np
def mat_in(n_arr,p,x):
    c=0
    for i in range(matrix_size):
        for j in range(matrix_size):
            if i==j:
                matrix[i, j] = p[x][c]
                c += 1
    return matrix
def permanent_function(mat):
    A = mat
# Generate all permutations of the indices (1, 2, 3, 4, 5)
    permutations = itertools.permutations(range(5))
# Calculate the permanent
    permanent_value = 0
    for perm in permutations:
        product = 1
        for i in range(5):
            product *= A[i, perm[i]]
        permanent_value += product
    return permanent_value
r=[]

for i in range(0,11):
    mat=mat_in(n_arr,n,i)
    per1=permanent_function(mat)
    r.append(per1)
print(mat)
print(r)

[[0.53566988 0.5        0.5        0.5        0.5       ]
 [0.5        0.64261739 0.5        0.5        0.5       ]
 [0.5        0.5        0.80064728 0.5        0.5       ]
 [0.5        0.5        0.5        0.79311203 0.5       ]
 [0.5        0.5        0.5        0.5        0.65134757]]
[4.092771957390182, 5.860000374422013, 5.7823372125473735, 4.45337784649858, 5.399748960584455, 6.2062926031707635, 3.6892153305836892, 3.711189389058847, 5.161818882262715, 5.533040375014668, 5.398169207277615]


In [13]:
#----------------RANKING THE CARS BASED ON THE PERMANENT FUNCTION CALCULATED-----------------
res={}
my_dict={}
keys=['Honda','Hyundai','Isuzu','Kia','Land-rover','Nexon','Porsche','Swift','Tata','Thar','Volvo']
i=0
for k in keys:
    my_dict[k]=r[i]
    i=i+1
i=0
print("CARS AFTER CALCULATING THE PERMANENT FUNCTION ")
for key, value in my_dict.items():
    print(f"{i} {key}: {value}")
#     print(value[0],' ',value[1],' ',value[2])
    i=i+1

print('-------CARS RANKED USING GTMA------')
i=1
sorted_dict = dict(sorted(my_dict.items(), key=lambda item: item[1], reverse=True))
for key, value in sorted_dict.items():
    print(f"{i} {key}: {value}")
    i=i+1


CARS AFTER CALCULATING THE PERMANENT FUNCTION 
0 Honda: 4.092771957390182
1 Hyundai: 5.860000374422013
2 Isuzu: 5.7823372125473735
3 Kia: 4.45337784649858
4 Land-rover: 5.399748960584455
5 Nexon: 6.2062926031707635
6 Porsche: 3.6892153305836892
7 Swift: 3.711189389058847
8 Tata: 5.161818882262715
9 Thar: 5.533040375014668
10 Volvo: 5.398169207277615
-------CARS RANKED USING GTMA------
1 Nexon: 6.2062926031707635
2 Hyundai: 5.860000374422013
3 Isuzu: 5.7823372125473735
4 Thar: 5.533040375014668
5 Land-rover: 5.399748960584455
6 Volvo: 5.398169207277615
7 Tata: 5.161818882262715
8 Kia: 4.45337784649858
9 Honda: 4.092771957390182
10 Swift: 3.711189389058847
11 Porsche: 3.6892153305836892
